services:
  - type: web
    name: paper-scorer
    runtime: python
    buildCommand: pip install -r req.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
